* When you find yourself in a hole,stop digging. — Will
* If you're waiting to have a good idea before you have any ideas, you won't have many ideas.
* The most experienced planner in the world is your brain.
* Don't just do something. Stand there. — Rochelle Myer
* People love to win. If you're not totally clear about the purpose of what you're doing, you have no chance of winning.
* Fanaticism Consists of redoubling your efforts when you have forgotten your aim. — George
* Celebrate any progress. Don't wait to get perfect. — Ann McGee Cooper
* If you're not sure why you're doing something, you can never do enough of it.
* Simple, clear purpose and principles give rise to complex and intelligent behavior. Complex rules and regulations give rise to simple and stupid behavior. — Dee
* Imagination is more important than knowledge. — Albert Einstein
* “How vain it is to sit down to write when you have not stood up to live!” — Henry David Thoreau
* you won't see how to do it  until you see yourself doing it.
* You often need to make it up in your mind before you can  make it happen in your life.
* I always wanted to be somebody. I should have been more specific. — Lily
* Nothing is more dangerous than an idea when it is the only one you have. — Emile Chartier
* Only he who handles his idea slightly is master of his ideas, and only he who is master of his ideas is not enslaved by them. — Lin Yutang
* Don't Judge, Challenge, Evaluate, or Criticize
* A good way to find out what something might be is to uncover all the things it's probably not.
* If the project is still on your mind,there's more planning to do.
* Thinking burns calories
* Experience is what you get when you didn't get what you wanted. — Randy Pausch
* First, think. Second, believe. Third, dream. And finally, dare. — Walt Disney
* You dont have to be great to start, but you have to start to be great. — Zig Ziglar
* Every great story on planet happened because someone decided not to give up, but kept going no matter what. — Spryte Loriano
* When you want to succeed as bad as you breathe, then you will be successful. — Eric Thomas
* Know who you are, and be it. Know what you want, and go out and get it. — Carroll Bryant
* Either you run the day or the day runs you. — Jim Rohn
* Success is not how high you have climbed, but how you make a positive difference to the world. — Roy T. Bennett
* A man who dares to waste one hour of his time has not discovered the value of life. — Charles Darwin
* You dont need a new day to start over. You only need a new Mindset.
* Its only after you have stepped outside your comfort zone that you begin to change grow and transform. — Roy T. Bennett
* If you can do what you do the best and be happy, you're further along in life than most people. - Leonardo DiCaprio
* You are not only responsible for what you say but also foe what you do not say. — Martin Luther
* The term 'checkmate' comes from the Arabic phrase 'shah mat' which means the king is dead
* Take responsibility of your own happiness, never put it in other people's hands. — Roy T. Bennett
* Be yourself; everyone else is already taken. — Oscar Wilde
* One resolution i have already made and try to always keep, is this: 'To rise above little things'. — John Burroughs
* Life is fragile. We're not guaranteed a tomorrow so give it everything you've got. — Tim Cook
* Angry people produce unique ideas faster than people in any other emotional state.
* He who has overcome his fears will truly be free. — Aristotle
* There is nothing either good or bad, but thinking makes it so. — William Shakespeare
* Consistency is the true foundation of trust. Either keep your promises or do not make them. — Roy T. Bennett
* What the mind can conceive and believe, and the heart desire, you can achieve. — Norman Vincent Peale
* Knowing right doesn't mean much unless you do what's right. — Theodore Roosevelt
* The meaning of life is to find your gift. The purpose of life is to give it away. — Pablo Picasso
* Success is a state of mind. If you want success, start thinking of yourself as success. — Joyce Brothers
* Collect moments. Not things
* I find that the harder I work, the more luck I seem to have. — Thomas Jefferson
* Do one thing everyday that scares you.
* Hold the vision. Trust the process.
* If you cant handle stress you won't manage success.
* Purpose is an incredible alarm clock.
* Making mistakes is better than faking perfections.
* Until you cross the bridge of your insecurities, you can't begin to explore your possibilities. — Tim Fargo
* Don't make excuses, make improvements. — Tyra Banks
* Everyone you meet has something to teach you.
* If you don't step forward, you will always remain in the same place.
* Long term consistency trumps short-trump intensity. — Bruce Lee
* Better an "oops" than a "what if".
* Cry a river. Build a bridge. Get over it.
* You were born to make an impact.
* Just because my path is different doesn’t mean I am lost.
* You may find the worst enemy or best friend in yourself.
* Speak less than you know; have more than you show. — William Shakespeare
* Do not go where the path may lead, go instead where there is no path and leave a trail. — Ralph Waldo Emerson
* Education costs money. But then so does ignorance. — Sir Claus Moser
* Hustle until your haters ask if you’re hiring.
* Never stop learning, because life never stops teaching.
* If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you. — Steve Jobs
* People who are crazy enough to think they can change the world, are the ones who do. — Rob Siltanen
* It does not matter how small you are if you have faith and a plan of action. — Fidel Castro
* Time goes on. So whatever you're going to do, do it. Do it now. Don't wait. — Robert De Niro
* Think big thoughts but relish small pleasures. — H. Jackson Brown, Jr.
* The two most powerful warriors are patience and time. — Leo Tolstoy
* The most important investment you can make is in yourself. — Warren Buffett
* It is the mark of an educated mind to be able to entertain a thought without accepting it. — Aristotle
* We are all different. Don’t judge, understand instead. — Roy T. Bennett
* Love all, trust a few, do wrong to none. — William Shakespeare
* If you don't throw yourself into something, you'll never know what you could have had. — Amy Winehouse
* Instinct is a marvelous thing. It can neither be explained nor ignored. — Agatha Christie
* Do what you feel in your heart to be right – for you’ll be criticized anyway. — Eleanor Roosevelt
* Count your age by friends, not years. Count your life by smiles, not tears. — John Lennon
* Any fool can know. The point is to understand. — Albert Einstein
* Knowledge speaks, but wisdom listens. — Jimi Hendrix
* I have not failed. I've just found 10,000 ways that won't work. — Thomas A. Edison
* Be brave to stand for what you believe in, even if you stand alone. — Roy T. Bennett
* Vision without execution is just hallucination. — Henry Ford
* If you believe you can, you might. If you know you can, you will. — Steve Maraboli
* He that can have patience can have what he will. — Benjamin Franklin
* Make improvements, not excuses. Seek respect, not attention. — Roy T. Bennett
* Realize deeply that the present moment is all you will ever have.  — Eckhart Tolle
* Life always begins with one step outside of your comfort zone. — Shannon L. Alder
* Pain is temporary. Quitting lasts forever. — Lance Armstrong
* Don't wait for things to happen. Make them happen. — Roy T. Bennett
* Plans get you into things but you've got to work your way out.
* You need no new skills to increase your productivity just a new set of behaviours about when and where to apply them.
* You increase your productivity and creativity exponentially when you think about the right things at the right time and have the tools to capture your value-added thinking.
* The compiler is our friend, our friend is the compiler!
* When you are writing a program you should assume nothing.
* A little bit of planning goes a long way, and can save us hours of re-working our code.
* Do. Or do not. There is no try. — Yoda
* “It does not do to dwell on dreams and forget to live.” — Albus Dumbledore
* Train yourself to notice and collect anything that doesn't belong where it is forever. — David Allen
* Process does not mean "spend time on".
* I am rather like a mosquito in a nudist camp; I know what I want to do, but I don't know where to begin. — Stephen Bayne
* I got it all together but i forgot where i put it.
* I would not give a fig for the simplicity this side of complexity, but I would give my life for the simplicity on the other side of complexity. — Oliver Wendell Holmes
* Those who make the worst use of their time are the first to complain of its shortness. — Jean de la Bruyere
* "Out of sight, out of mind" is not really out mind of. — Daivd Allen
* Give me six hours to chop down a tree and I will spend the first four sharpening the axe. — Abraham Lincoln
* First-rate people hire first-rate people; second-rate people hire third-rate people. — Leo Rosten
* I hire people brighter than me and I get out of their way. — Leo lacocca
* What lies in our power to do, lies in our power not to do.
* To make knowledge productive, we will have to learn to see both  forest and tree. We will have to learn to connect. — Peter F.
* "Point of view" is that qulntessentially human solution to information overload, an intuitive process of reducing things to an essential relevant and manageable minimum. . . . In a world of hyperabundant content, point of view will become the scarcest of resources. — Paul
* We all have times when we think more effectively, and times when we should not bethinking at all. — Daniel Cohen
* There is no reason not to be highly productive, even when you're not in top form.
* To ignore the unexpected (even if it were possible) would be to live without opportunity, spontaneity, and the rich moments of which "life" is made. — Stephen Covey
* Your work is to discover your work and then with all your heart to give yourself to it.
* The best place to succeed is where you are with what you have. — Charles
* When you're not sure where you're going, you'll never know when enough is enough.
* The middle of every successful project looks like a disaster. — Rosabeth Moss
* Luck affects everything. Let your hook always be cast; in the stream where you least expect it there will be a fish.
* How do I know what I think, until I hear what I say? — E. M. Forster
* Outstanding people have one thing in common: an absolute sense of Mission. — Zig Ziglar
* The level of success you achieve will be in direct proportion to the depth of your commitment. — Roy T. Bennett
* Solve the problem or leave the problem, but do not sleep with the problem.
* It's not what's under the Christmas Tree that matters, it's who's around it. — Charlie Brown
* If you want to live a happy life, tie it to a goal, not to people or things. — Albert Einstein
* Let our advance worrying become advance thinking and planning. — Winston Churchill
* It is the act of forgiveness that opens up the only possible way to think creatively about the future at all. — Father
* The secret of getting ahead is getting started. The secret of getting started is breaking your complex overwhelming tasks into small manageable tasks,and then starting on the first one. — Mark Twain
* Bright people have the capability of freaking out faster and more dramatically than anyone else.
* I am an old man and have known a great many troubles, but most of them never happened. — Mark Twain
* No matter how big and tough a problem may be, get rid of confusion by taking one little step toward solution. Do something. — George F.
* You can only cure retail but you can prevent wholesale. — Brock Chisolm
* Talk does not cook rice. — Chinese
* People are always blaming their circumstances for what they are. I don't believe in circumstances. The People who get on in this world are the people who getup and look for the circumstances they want, and, if they can't find them, they make them. — George BernardShaw
* Revenge is a dish that tastes best when served cold. — The Godfather
* An idealist believes that the short run doesn't count. A cynic believes the long run doesn't matter.
* A realist believes that what is done or left undone in the short run determines the long run. — Sidney.
* A vision without a task is but a dream, a task without a vision is drudgery, a vision and a task is the hope of the world. — From a church in Sussex, England, ca.1730
* One day, in retrospect, the years of struggle will strike you as the most beautiful. — Sigmund Freud
* If A equals success, then the formula is A equals X plus Y plus Z. X is work. Y is play. Z is keep your mouth shut — Albert Einstein
* The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time. ― Eric Mark Twain
* Seek the truth for yourself, and I will meet you there. — Josh
* I would rather have questions that can't be answered than answers that can't be questioned. — Professor Richard Feynman
* The code you write makes you a programmer. The code you delete makes you a good one. The code you don't have to write makes you a great one. — Mario Fusco
* Our imagination is stretched to the utmost, not, as in fiction, to imagine things which are not really there, but just to comprehend those things which are. — Richard Feynman
* Some people, when confronted with a problem, think I know, I'll use regular expressions. Now they have two problems. — Jamie Zawinski
* If there is any one secret of success, it lies in the ability to get the other person's point of view and see things from that person's angle as well as from your own. — Henry Ford
* It is the individual who is not interested in his fellow men who has the greatest difficulties in life and provides the greatest injury to others. It is from among such individuals that all human failures spring. — Alfred Adler
* A man without a smiling face must not open a shop.
* A man convinced against his will Is of the same opinion still.
* You cannot teach a man anything;  you can only help him to find it within himself. — Galileo
* One thing only I know, and that is that I know nothing. — Socrates
* By fighting you never get enough, but by yielding you get more than you expected.
* He who treads softly goes far.
* If you want enemies, excel your friends; but if you want friends, let your friends excel you. — La Rochefoucauld
* The greatest of richness is the richness of the soul. — Prophet Muhammad
* Life isn't about getting and having, it's about giving and being. — Kevin Kruse
* Don't count the days, make the days count. — Muhammad Ali
* Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it. — Rumi
* Thinking is hard work; that's why so few do it. — Albert Einstein
* I can give you a six-word formula for success: Think things through, then follow through. — Eddie Rickenbacker
* Learning to  write is learning to think. You don't  know anything clearly unless  youcan state it in writing. — Hayakawa
* The Right Thought plus the Right People in the Right Environment at the Right Time for the Right Reason = the Right Result.
* He that is everywhere is nowhere. — Thomas Fuller
* He did each thing as if he did nothing else. — Charles Dickens
* If you can't write your idea on the back of my business card, you don't have a clear idea. — David Belasco
* The joy is in creating, not maintaining. — Vincr Lombardi
* Creative thinking works something  like this: THINK _ COLLECT _ CREATE _  CORRECT _ CONNECT
* The first responsibility of a leader is to define reality. — Max Depree
* Until thought is linked with purpose there is no intelligent accomplishment. — James Allen
* Idealism increases in direct proportion to one's distance from the problem. — John Galsworthy
* Men occasionally stumble over the truth, but most pick themselves up and hurry off as if nothing has  happened. — Wintson Churchill
* Deliberate with caution, but act with decision; and yield with graciousness or oppose with firmness. — Charles Hole
* The man who is prepared has his battle half fought. — Miguel de Cervantes
* Thousands of engineers can design bridges, calculate strains and stresses, and draw up specificatins for machines, but the great engineer is the man who can tell whether the bridge or the machine should be build at all, where it should be build, and when. — Eugene G. Grace
* Before it can be solved, a problem must be clearly defined — William Feather
* The will to win is worthless if you do not have the will to prepare. — Thane Yost
* If I have 100 hours to solve a problem, I'll spend 95 hours thinking about it (defining it), and 5 hours actually solving it. — Albert Einstein
* Nothing is so embarrasing as watching someone do something that you said could not be done. — Sam Ewing
* We ought not to look back unless it is to derive useful lessons from past errors, for the purpose of profiting by dearly bought experience. — George Washington
* Experience is a jewel, and it had need be so, for it is often purchased at an infinite rate. — William Shakespeare
* We should be careful to get out of an experience all the wisdom that is in it; not like the cat that sits down on a hot stove lid. She will never sit down on a hot stove lid again; and that is well; but also she will never sit down on a cold one anymore — Mark Twain
* The unexamind life is not worth living. — Socrates
* I'm not an answering machine, I'm a questioning machine. If we have all the answers, howcome we're in such a mess? — Douglas Cardinal
* None of us is as smart as all of us. — Klen Blanchard
* Many times a day I realize how much my own outer and inner life is built upon the labors of my fellow men, both living and dead, and how earnestly I must exert myself in order to give in return as much as I have received. — Albert Einstein
* To accept good advice is but to increase one's own ability. — Johann Wolfgang von Goethe
* He that is taught only by himself has a fool for a master. — Ben Johnson
* If we each have one thought, and together we have two thoughts, then we always have the potential for a great thought. — John C. Maxwell
* Listening to advice often accomplishes far more than heeding it. — Malcolm Forbes
* We cannot hold a torch to light another's path without brightening our own. — Ben Sweetland
* Getters generally don't get happiness; givers get it. — Charles H. Burr
* There is no more noble occupation in the world than to assist another human being to help someone succeed. — Alan Loy McGinnis
* People with humility don't think less of themselves; they just think of themselves less. — Ken Blanchard and Norman Vincent Peale
* There ain't no rules around here. We're trying to accomplish something. — Thomas Edison
* Everything begins with a thought. — John C. Maxwell
* Life consists of what a man is thinking about all day. — Ralph Waldo Emerson
* What we think determines who we are. Who we are determines what we do. — John C. Maxwell
* The actions of men are the best interpreters of their thoughts. — John Locke
* Our thoughts determine our destiny. Our destiny determines our legacy. — John C. Maxwell
* You are today where your thoughts have brought you. You will be tomorrow where your thoughts take you. — James Allen
* People who go to the top think differently than others. — John C. Maxwell
* Nothing limits achievement like small thinking; Nothing expands possibilities like unleashed thinking. — William Arthur Ward
* We can change the way we think. — John C. Maxwell
* Whatever things are true, noble, just, pure, lovely, are of good report. If there is any virtue and if there is anything praiseworthy; think on these things. — Paul The Apostle
* If you think you are too small to make a difference, try sleeping with a mosquito. — Dalai Lama
* You can't use up creativity. The more you use, the more you have. — Maya Angelou
* Do what you love. There is no excuse not to do what makes you happy.
* All life is an experiment. The more experiments you make the better. — Ralph Waldo Emerson
* What we achieve ineardly will change outer reality. — Plutarch
* Remember that not getting what you want is sometimes a wonderful stroke of luck. — Dalai Lama
* If life were predictable it would cease to be life, and be without flavour. — Eleanor Roosevelt
* If you don't have room to fail, you don't have room to grow. — Johnathan Mildenhall
* We are what we do repeatedly. Excellence, then, is not an act, but a habit. — Aristotle
* Your future is created by what tou do today, not tomorrow. — Robert Kiyosaki
* Success comes from having your dreams bigger than your fears. — Terry Litwiller
* The world is a book, and those who do not travel read only a page. — Saint Augustine
* Being a good developer is a great dream but being a good java developer is not.
* The most important thing is never stop believing.
* We have to dare to be ourselves, however frightening or strange that self may prove to be. — May Sarton
* Do not tell the world what you can do - show it!
* Grind while they rest. Study when they party. You will live like they dream. — Grant Cardone
* Live is inherently risky. There is only big risk that you should avoid at all costs, and that is doing nothing. — Denis Waitley
* Procrastination is the thief of time, collar him. — Charles Dickens
* Live boldly. Push yourself. Don't settle. — Jojo Moyes
* Obstacles are those frightful things you see when you take your eyes off your goal. — Henry Ford
* Too many of us are not living our dreams cause we are living our fears. — Les Brown
* Be humble. Be hungry. And always be the hardest worker in the room. — Dwayne Johnson
* The only person you are destined to become is the person you decide to be. — Ralph Waldo Emerson
* Life is 10% what happens to me and 90% how i react to it. — Charles Swindoll
* Dreaming of the person you want to be is wasting the person you already are. — Kurt Cobain
* The man who asks a question is fool for a minute, the man who does not ask is a fool for life. — Confucius
* One must always be prepared for riotous and endless waves of transformation. — Elizabeth Gilbert
* Embrace uncertainty. Some of the most beautiful chapters in our lives won't have a title until much later. — Bon Golf
* If you don't give up on something you truly believe in, you will find a way. — Roy T Bennett.
* Strive for excellence in few things, rather than good performance in many. — Richard Koch
* Be an encourager. The world has plenty of critics already. — Dave Wills
* If you don't stand for something you will fall for anything. — Gordon A. Eadie
* Fight and push harder for what you believe in, you'd be surprised, you are much stronger than you think. — Lady Gaga
* Accept what is, let go of what was and have faith in what could be.
* True excellence is marked not by how great you are, but by how great you make those around you. — Kate Heddleston's Coach
* Your ability to win is the sum of your talent multiplied by how well you work together as a team. Ability to Win = Σ(talent) * teamwork. Modified for the work world, this equation looks like this: Productivity = Σ(talent) * teamwork. — Kate Heddleston.
* Make things as simple as possible, but not simpler. — Albert Einstein
* Bravery is doing what is right even when it's not popular.
* Allow yourself to be a beginner. No one starts off being excellent. — Wendy Flynn
* When you make a commitment you build hope. When you keep it, you build trust.
* Life isn't about finding yourself. Life is about creating yourself. — George Bernard Shaw
* Happiness depends on being free, and freedom depends on being courageous. — Marie Rutkoski
* Success is to wake up each morning and consciously decide that today will be the best day of your life. — Ken Poirot
* Soar with wit. Conquer with dignity. Handle with care. — Criss Jamie
* A man who has confidence in himself, gains the confidence of others.
* One way to keep momentum going is to have constantly greater goals. — Michael Korda
* Live life as tough nobody is watching, and express yourself as tough every one is listening. — Nelson Mandela
* If you want the best the world has to offer, offer the world your best. — Neale Donald Walsch
* The past is a place of reference, not a place of residence; the past is a place of learning, not a place of living. — Roy T. Bennett
* Always remember, your focus determines your reality. — George Lucas
* Motivation comes from working on things we care about. — Sheryl Sandberg
* Nothing can disturb your piece of mind unless you allow it too. — Roy T. Bennett
* Cultivation of mind should be the ultimate aim of human existence. — B.R. Ambedkar
* Don't wait. The time will never be just right. — Napoleon Hill
* Choose being kind over being right and you'll be right every time. — Richard Carlson
* Do you want to know who you are? Don't ask. Act! Action will delineate and define you. — Thomas Jefferson
* Whatever level you reach, getting better never stops. — Sachin Tendulkar
* The implementation that’s quickest to write is rarely the quickest to run. — Robert Nystrom
* Change may not always bring growth, but there is no growth without change. — Roy T. Bennett
* Accept yourself irrespective of your imperfection and express your skills. — Israelmore Ayivor
* You were born to stand out, stop trying to fit in. — Roy T. Bennett
* Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship. — Gautama Buddha
* Do the thing you fear and the death of fear is certain. — Ralph Waldo Emerson
* Until you step into the unknown, you don't know what you're made of. — Roy T. Bennett
* Obstacles are things a person sees when he takes his eyes off his goal. — E. Joseph Cossman
* Champions are made from something they have deep inside them – a desire, a dream, a vision. — Muhammad Ali
* A minute's success pays the failure of years. — Robert Browning
* The worst enemy of our humanity is our self-doubt. — Lolly Daskal
* Change your life today. Don't gamble on the future, act now, without delay. — Simone de Beauvoir
* You got to train your mind to be stronger than your emotions or else you'll lose yourself every time.
* The less you respond to negative people, the more peaceful your life will become.
* Take risks: if you win, you will be happy; if you lose, you will be wise.
* You are the artist of your life. Don't give the paintbrush to anyone else.
* The comeback is always stronger than the setback.
* Open your mind before your mouth.
* In life have a friend that is like a mirror and shadow. Mirror doesn't lie and shadow never leaves.
* If you don't sacrifice for what you want, what you want will be the sacrifice.
* Every next level of your life will demand a different version of you.
* If you don't have time, you don't have priorities. — Tim Ferriss
* To achieve something you have never achieved before you must become someone you have never been. — Les Brown
* To succeed in life, you need two things: ignorance and confidence. — Mark Twain
* Everything falls just in place when you continue to do the thing you love doing, irrespective of what the world says.
* Be happy with who you are and what you do, and you can do anything you want. — Steve Maraboli
* Strength grows in the moments when you think you can't go on but you keep going anyway.
* It costs you nothing to believe in yourself. But it will cost you everything if you don't. — Joel Brown
* It is not the mountain we conquer but ourselves. — Edmund Hillary
* One of the happiest moments in life is when you find the courage to let go of what you can't change.
* You were never created to live depressed, defeated, guilty, condemned, ashamed, or unworthy. You were created to be victorious. — Joel Osteen
* A father is someone you look up to no matter how tall you grow.
* We don't grow when things are easy. We grow when we face challenges. — Joyce Meyer
* Eventually all things fall into place. Until then, laugh at the confusion, live for the moments and know everything happens for a reason. — Albert Schweitzer
* Starting today, I need to forget what's gone. Appreciate what still remains and look forward to what's coming next.
* Worrying does not empty tomorrow of its troubles. It empties today of its strength. — Corrie Ten Boom
* If it doesn't challenge you, it doesn't change you. — Fred Devito
* When you surround yourself with positive people who are making a difference in the world, you start to believe anything is possible. — Steven Aitchison
* Life will only change when you become more committed to your dreams than you are to your comfort zone. — Billy Cox
* Pick yourself up, dust yourself off and start again.
* In three words I can sum up everything I've learned about life, it goes on. — Robert Frost
* It is better to be hated for what you are than to be loved for what you are not. — Andre Gide
* Anyone who lives within their means suffers from a lack of imagination. — Oscar Wilde
* Life's under no obligation to give us what we expect. — Margaret Mitchell
* You must trust and believe in people or life becomes impossible. — Anton Chekhov
* In the realm of ideas everything depends on enthusiasm. In the real world all rests on perseverance. — Johann Wolfgang von Goethe
* To live a creative life, we must lose our fear of being wrong. — Joseph Chilton Pearce
* All that we are is a result of what we have thought. — Buddh
* Definiteness of purpose is the starting point of all achievement. — W. Clement Stone
* The only time success comes before work is in the dictionary. — Vince Lombardi
* It is possible to commit no mistakes and still lose. That is not a weakness; that is life. — Jean-Luc Picard
* Never forget what you are. The rest of the world will not. Wear it like armour, and it can never be used to hurt you. — Tyrion Lannister
* Everything will be okay in the end. If it's not okay, it's not the end. — John Lennon
* You have to get to that point where your mood doesn't shift based on insignificant actions of someone else.
* Don't limit your challenges; challenge your limits. — Jerry Dunn
* Success is not for the lazy.
* When you stop chasing the wrong things you give the right things a chance to catch you. — Lolly Daskal
* Surround yourself with people who have dreams, desires and ambitions; they will help you find your own and help you push towards them.
* Do not overestimate the competition and underestimate yourself. You are better than you think. — Tim Ferriss
* A real friend is one who walks in when rest of the world walks out. — Walter Winchel
* Some people go to priests; others to poetry; I to my friends. —
* True friendship comes when the silence between two people is comfortable. — Dave Tyson Gentry
* He who controls others may be powerful, but he who has mastered himself is mightier still. — Tao Te Ching
* If the plan doesn't work, change the plan but not the goal.
* Look back in forgiveness, forward in hope, down in compassion and up with gratitude. — Zig Ziglar
* It's hard to beat a person who never gives up. — Babe Ruth
* Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy. — Norman Vincent Peale
* Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine. — Roy T. Bennett
* Your true success in life begins only when you make the commitment to become excellent at what you do. — Brian Tracy
* You have the power to change anything because you are the one who chooses your thoughts and you are the one who feels your feelings. — Rhonda Byrne
* Re-set, re-adjust, re-start, re-focus as many times as you need to.
* When we think we know, we cease to learn. — Sarvepalli Radhakrishnan
* Before you give up, think of the reason why you held on so long.
* I learned that courage was not the absence of fear, but the triumph over it. The brave man is not he who does not feel afraid, but he who conquers that fear. — Nelson Mandela
* Do not be pushed around by the fears in your mind. Be led by the dreams in your heart. — Roy T. Bennett
* If you believe it will work out, you'll see opportunities. If you believe it won't, you will see obstacles. — Wayne Dyer
* Hard times don't create heroes. It is during the hard times when the 'hero' within us is revealed. — Bob Riley
* I attribute my success to this: I never gave or took any excuse. — Florence Nightingale
* Whatever you hold in your mind on a consistent basis is exactly what you will experience in your life. — Tony Robbins
* It is during our darkest moments that we must focus to see the light. — Aristotle Onassis
* Be a student as long as you still have something to learn, and this will mean all your life. — Henry L. Doherty
* Challenges are what make life interesting and overcoming them is what makes life meaningful. — Joshua Marine
* When obstacles arise, you change your direction to reach your goal, you do not change your decision to get there. — Zig Ziglar
* No matter how hard times may get, always hold your head up and be strong; show them you're not as weak as they think you are.
* It's not about perfect. It's about effort. And when you bring that effort every single day, that's where transformation happens. That's how change occurs. — Jillian Michaels
